### PR TITLE
Updated ServicePrincipalAppRole customizations (#1161)

### PR DESCRIPTION
**Pull request by alflokken**
Updated ServicePrincipalAppRole customizations (#1161)

### CODE REVIEW

**Comment by alflokken** [comment]
@microsoft-github-policy-service agree

**Comment by SteveMutungi254** [comment]
@alflokken: Thanks so much for your contributions! We're reviewing the PR, and if all goes smoothly, this change will be included in the next release.

**Review by SteveMutungi254 — APPROVED** [review]
LGTM.

**Review by KenitoInc — APPROVED** [review]

**Review by SteveMutungi254 — APPROVED** [review]
LGTM.

**Pull request merged**
